//  Copyright (c) 2015 ICRL
//  See the file LICENSE.txt for copying permission.
//
//  VCMaterialDesignIcons.m
//  Lifebit
//
//  Created by twidle on 2/26/15.
//  Copyright (c) 2015 Fufu Labs. All rights reserved.
//

#import "VCMaterialDesignIcons.h"
#import <CoreText/CoreText.h>

const struct VCMaterialDesignIconCode VCMaterialDesignIconCode = {
  .md_3d_rotation                 = @"\uf000",
  .md_accessibility               = @"\uf001",
  .md_account_balance             = @"\uf002",
  .md_account_balance_wallet      = @"\uf003",
  .md_account_box                 = @"\uf004",
  .md_account_child               = @"\uf005",
  .md_account_circle              = @"\uf006",
  .md_add_shopping_cart           = @"\uf007",
  .md_alarm                       = @"\uf008",
  .md_alarm_add                   = @"\uf009",
  .md_alarm_off                   = @"\uf00a",
  .md_alarm_on                    = @"\uf00b",
  .md_android                     = @"\uf00c",
  .md_announcement                = @"\uf00d",
  .md_aspect_ratio                = @"\uf00e",
  .md_assessment                  = @"\uf00f",
  .md_assignment                  = @"\uf010",
  .md_assignment_ind              = @"\uf011",
  .md_assignment_late             = @"\uf012",
  .md_assignment_return           = @"\uf013",
  .md_assignment_returned         = @"\uf014",
  .md_assignment_turned_in        = @"\uf015",
  .md_autorenew                   = @"\uf016",
  .md_backup                      = @"\uf017",
  .md_book                        = @"\uf018",
  .md_bookmark                    = @"\uf019",
  .md_bookmark_outline            = @"\uf01a",
  .md_bug_report                  = @"\uf01b",
  .md_cached                      = @"\uf01c",
  .md_class                       = @"\uf01d",
  .md_credit_card                 = @"\uf01e",
  .md_dashboard                   = @"\uf01f",
  .md_delete                      = @"\uf020",
  .md_description                 = @"\uf021",
  .md_dns                         = @"\uf022",
  .md_done                        = @"\uf023",
  .md_done_all                    = @"\uf024",
  .md_event                       = @"\uf025",
  .md_exit_to_app                 = @"\uf026",
  .md_explore                     = @"\uf027",
  .md_extension                   = @"\uf028",
  .md_face_unlock                 = @"\uf029",
  .md_favorite                    = @"\uf02a",
  .md_favorite_outline            = @"\uf02b",
  .md_find_in_page                = @"\uf02c",
  .md_find_replace                = @"\uf02d",
  .md_flip_to_back                = @"\uf02e",
  .md_flip_to_front               = @"\uf02f",
  .md_get_app                     = @"\uf030",
  .md_grade                       = @"\uf031",
  .md_group_work                  = @"\uf032",
  .md_help                        = @"\uf033",
  .md_highlight_remove            = @"\uf034",
  .md_history                     = @"\uf035",
  .md_home                        = @"\uf036",
  .md_https                       = @"\uf037",
  .md_info                        = @"\uf038",
  .md_info_outline                = @"\uf039",
  .md_input                       = @"\uf03a",
  .md_invert_colors               = @"\uf03b",
  .md_label                       = @"\uf03c",
  .md_label_outline               = @"\uf03d",
  .md_language                    = @"\uf03e",
  .md_launch                      = @"\uf03f",
  .md_list                        = @"\uf040",
  .md_lock                        = @"\uf041",
  .md_lock_open                   = @"\uf042",
  .md_lock_outline                = @"\uf043",
  .md_loyalty                     = @"\uf044",
  .md_markunread_mailbox          = @"\uf045",
  .md_note_add                    = @"\uf046",
  .md_open_in_browser             = @"\uf047",
  .md_open_in_new                 = @"\uf048",
  .md_open_with                   = @"\uf049",
  .md_pageview                    = @"\uf04a",
  .md_payment                     = @"\uf04b",
  .md_perm_camera_mic             = @"\uf04c",
  .md_perm_contact_cal            = @"\uf04d",
  .md_perm_data_setting           = @"\uf04e",
  .md_perm_device_info            = @"\uf04f",
  .md_perm_identity               = @"\uf050",
  .md_perm_media                  = @"\uf051",
  .md_perm_phone_msg              = @"\uf052",
  .md_perm_scan_wifi              = @"\uf053",
  .md_picture_in_picture          = @"\uf054",
  .md_polymer                     = @"\uf055",
  .md_print                       = @"\uf056",
  .md_query_builder               = @"\uf057",
  .md_question_answer             = @"\uf058",
  .md_receipt                     = @"\uf059",
  .md_redeem                      = @"\uf05a",
  .md_report_problem              = @"\uf05b",
  .md_restore                     = @"\uf05c",
  .md_room                        = @"\uf05d",
  .md_schedule                    = @"\uf05e",
  .md_search                      = @"\uf05f",
  .md_settings                    = @"\uf060",
  .md_settings_applications       = @"\uf061",
  .md_settings_backup_restore     = @"\uf062",
  .md_settings_bluetooth          = @"\uf063",
  .md_settings_cell               = @"\uf064",
  .md_settings_display            = @"\uf065",
  .md_settings_ethernet           = @"\uf066",
  .md_settings_input_antenna      = @"\uf067",
  .md_settings_input_component    = @"\uf068",
  .md_settings_input_composite    = @"\uf069",
  .md_settings_input_hdmi         = @"\uf06a",
  .md_settings_input_svideo       = @"\uf06b",
  .md_settings_overscan           = @"\uf06c",
  .md_settings_phone              = @"\uf06d",
  .md_settings_power              = @"\uf06e",
  .md_settings_remote             = @"\uf06f",
  .md_settings_voice              = @"\uf070",
  .md_shop                        = @"\uf071",
  .md_shopping_basket             = @"\uf072",
  .md_shopping_cart               = @"\uf073",
  .md_shop_two                    = @"\uf074",
  .md_speaker_notes               = @"\uf075",
  .md_spellcheck                  = @"\uf076",
  .md_star_rate                   = @"\uf077",
  .md_stars                       = @"\uf078",
  .md_store                       = @"\uf079",
  .md_subject                     = @"\uf07a",
  .md_swap_horiz                  = @"\uf07b",
  .md_swap_vert                   = @"\uf07c",
  .md_swap_vert_circle            = @"\uf07d",
  .md_system_update_tv            = @"\uf07e",
  .md_tab                         = @"\uf07f",
  .md_tab_unselected              = @"\uf080",
  .md_theaters                    = @"\uf081",
  .md_thumb_down                  = @"\uf082",
  .md_thumbs_up_down              = @"\uf083",
  .md_thumb_up                    = @"\uf084",
  .md_toc                         = @"\uf085",
  .md_today                       = @"\uf086",
  .md_track_changes               = @"\uf087",
  .md_translate                   = @"\uf088",
  .md_trending_down               = @"\uf089",
  .md_trending_neutral            = @"\uf08a",
  .md_trending_up                 = @"\uf08b",
  .md_turned_in                   = @"\uf08c",
  .md_turned_in_not               = @"\uf08d",
  .md_verified_user               = @"\uf08e",
  .md_view_agenda                 = @"\uf08f",
  .md_view_array                  = @"\uf090",
  .md_view_carousel               = @"\uf091",
  .md_view_column                 = @"\uf092",
  .md_view_day                    = @"\uf093",
  .md_view_headline               = @"\uf094",
  .md_view_list                   = @"\uf095",
  .md_view_module                 = @"\uf096",
  .md_view_quilt                  = @"\uf097",
  .md_view_stream                 = @"\uf098",
  .md_view_week                   = @"\uf099",
  .md_visibility                  = @"\uf09a",
  .md_visibility_off              = @"\uf09b",
  .md_wallet_giftcard             = @"\uf09c",
  .md_wallet_membership           = @"\uf09d",
  .md_wallet_travel               = @"\uf09e",
  .md_work                        = @"\uf09f",
  .md_error                       = @"\uf0a0",
  .md_warning                     = @"\uf0a1",
  .md_album                       = @"\uf0a2",
  .md_av_timer                    = @"\uf0a3",
  .md_closed_caption              = @"\uf0a4",
  .md_equalizer                   = @"\uf0a5",
  .md_explicit                    = @"\uf0a6",
  .md_fast_forward                = @"\uf0a7",
  .md_fast_rewind                 = @"\uf0a8",
  .md_games                       = @"\uf0a9",
  .md_hearing                     = @"\uf0aa",
  .md_high_quality                = @"\uf0ab",
  .md_loop                        = @"\uf0ac",
  .md_mic                         = @"\uf0ad",
  .md_mic_none                    = @"\uf0ae",
  .md_mic_off                     = @"\uf0af",
  .md_movie                       = @"\uf0b0",
  .md_my_library_add              = @"\uf0b1",
  .md_my_library_books            = @"\uf0b2",
  .md_my_library_music            = @"\uf0b3",
  .md_new_releases                = @"\uf0b4",
  .md_not_interested              = @"\uf0b5",
  .md_pause                       = @"\uf0b6",
  .md_pause_circle_fill           = @"\uf0b7",
  .md_pause_circle_outline        = @"\uf0b8",
  .md_play_arrow                  = @"\uf0b9",
  .md_play_circle_fill            = @"\uf0ba",
  .md_play_circle_outline         = @"\uf0bb",
  .md_playlist_add                = @"\uf0bc",
  .md_play_shopping_bag           = @"\uf0bd",
  .md_queue                       = @"\uf0be",
  .md_queue_music                 = @"\uf0bf",
  .md_radio                       = @"\uf0c0",
  .md_recent_actors               = @"\uf0c1",
  .md_repeat                      = @"\uf0c2",
  .md_repeat_one                  = @"\uf0c3",
  .md_replay                      = @"\uf0c4",
  .md_shuffle                     = @"\uf0c5",
  .md_skip_next                   = @"\uf0c6",
  .md_skip_previous               = @"\uf0c7",
  .md_snooze                      = @"\uf0c8",
  .md_stop                        = @"\uf0c9",
  .md_subtitles                   = @"\uf0ca",
  .md_surround_sound              = @"\uf0cb",
  .md_videocam                    = @"\uf0cc",
  .md_videocam_off                = @"\uf0cd",
  .md_video_collection            = @"\uf0ce",
  .md_volume_down                 = @"\uf0cf",
  .md_volume_mute                 = @"\uf0d0",
  .md_volume_off                  = @"\uf0d1",
  .md_volume_up                   = @"\uf0d2",
  .md_web                         = @"\uf0d3",
  .md_business                    = @"\uf0d4",
  .md_call                        = @"\uf0d5",
  .md_call_end                    = @"\uf0d6",
  .md_call_made                   = @"\uf0d7",
  .md_call_merge                  = @"\uf0d8",
  .md_call_missed                 = @"\uf0d9",
  .md_call_received               = @"\uf0da",
  .md_call_split                  = @"\uf0db",
  .md_chat                        = @"\uf0dc",
  .md_clear_all                   = @"\uf0dd",
  .md_comment                     = @"\uf0de",
  .md_contacts                    = @"\uf0df",
  .md_dialer_sip                  = @"\uf0e0",
  .md_dialpad                     = @"\uf0e1",
  .md_dnd_on                      = @"\uf0e2",
  .md_email                       = @"\uf0e3",
  .md_forum                       = @"\uf0e4",
  .md_import_export               = @"\uf0e5",
  .md_invert_colors_off           = @"\uf0e6",
  .md_invert_colors_on            = @"\uf0e7",
  .md_live_help                   = @"\uf0e8",
  .md_location_off                = @"\uf0e9",
  .md_location_on                 = @"\uf0ea",
  .md_message                     = @"\uf0eb",
  .md_messenger                   = @"\uf0ec",
  .md_no_sim                      = @"\uf0ed",
  .md_phone                       = @"\uf0ee",
  .md_portable_wifi_off           = @"\uf0ef",
  .md_quick_contacts_dialer       = @"\uf0f0",
  .md_quick_contacts_mail         = @"\uf0f1",
  .md_ring_volume                 = @"\uf0f2",
  .md_stay_current_landscape      = @"\uf0f3",
  .md_stay_current_portrait       = @"\uf0f4",
  .md_stay_primary_landscape      = @"\uf0f5",
  .md_stay_primary_portrait       = @"\uf0f6",
  .md_swap_calls                  = @"\uf0f7",
  .md_textsms                     = @"\uf0f8",
  .md_voicemail                   = @"\uf0f9",
  .md_vpn_key                     = @"\uf0fa",
  .md_add                         = @"\uf0fb",
  .md_add_box                     = @"\uf0fc",
  .md_add_circle                  = @"\uf0fd",
  .md_add_circle_outline          = @"\uf0fe",
  .md_archive                     = @"\uf0ff",
  .md_backspace                   = @"\uf000",
  .md_block                       = @"\uf101",
  .md_clear                       = @"\uf102",
  .md_content_copy                = @"\uf103",
  .md_content_cut                 = @"\uf104",
  .md_content_paste               = @"\uf105",
  .md_create                      = @"\uf106",
  .md_drafts                      = @"\uf107",
  .md_filter_list                 = @"\uf108",
  .md_flag                        = @"\uf109",
  .md_forward                     = @"\uf10a",
  .md_gesture                     = @"\uf10b",
  .md_inbox                       = @"\uf10c",
  .md_link                        = @"\uf10d",
  .md_mail                        = @"\uf10e",
  .md_markunread                  = @"\uf10f",
  .md_redo                        = @"\uf110",
  .md_remove                      = @"\uf111",
  .md_remove_circle               = @"\uf112",
  .md_remove_circle_outline       = @"\uf113",
  .md_reply                       = @"\uf114",
  .md_reply_all                   = @"\uf115",
  .md_report                      = @"\uf116",
  .md_save                        = @"\uf117",
  .md_select_all                  = @"\uf118",
  .md_send                        = @"\uf119",
  .md_sort                        = @"\uf11a",
  .md_text_format                 = @"\uf11b",
  .md_undo                        = @"\uf11c",
  .md_access_alarm                = @"\uf11d",
  .md_access_alarms               = @"\uf11e",
  .md_access_time                 = @"\uf11f",
  .md_add_alarm                   = @"\uf120",
  .md_airplanemode_off            = @"\uf121",
  .md_airplanemode_on             = @"\uf122",
  .md_battery_20                  = @"\uf123",
  .md_battery_30                  = @"\uf124",
  .md_battery_50                  = @"\uf125",
  .md_battery_60                  = @"\uf126",
  .md_battery_80                  = @"\uf127",
  .md_battery_90                  = @"\uf128",
  .md_battery_alert               = @"\uf129",
  .md_battery_charging_20         = @"\uf12a",
  .md_battery_charging_30         = @"\uf12b",
  .md_battery_charging_50         = @"\uf12c",
  .md_battery_charging_60         = @"\uf12d",
  .md_battery_charging_80         = @"\uf12e",
  .md_battery_charging_90         = @"\uf12f",
  .md_battery_charging_full       = @"\uf130",
  .md_battery_full                = @"\uf131",
  .md_battery_std                 = @"\uf132",
  .md_battery_unknown             = @"\uf133",
  .md_bluetooth                   = @"\uf134",
  .md_bluetooth_connected         = @"\uf135",
  .md_bluetooth_disabled          = @"\uf136",
  .md_bluetooth_searching         = @"\uf137",
  .md_brightness_auto             = @"\uf138",
  .md_brightness_high             = @"\uf139",
  .md_brightness_low              = @"\uf13a",
  .md_brightness_medium           = @"\uf13b",
  .md_data_usage                  = @"\uf13c",
  .md_developer_mode              = @"\uf13d",
  .md_devices                     = @"\uf13e",
  .md_dvr                         = @"\uf13f",
  .md_gps_fixed                   = @"\uf140",
  .md_gps_not_fixed               = @"\uf141",
  .md_gps_off                     = @"\uf142",
  .md_location_disabled           = @"\uf143",
  .md_location_searching          = @"\uf144",
  .md_multitrack_audio            = @"\uf145",
  .md_network_cell                = @"\uf146",
  .md_network_wifi                = @"\uf147",
  .md_nfc                         = @"\uf148",
  .md_now_wallpaper               = @"\uf149",
  .md_now_widgets                 = @"\uf14a",
  .md_screen_lock_landscape       = @"\uf14b",
  .md_screen_lock_portrait        = @"\uf14c",
  .md_screen_lock_rotation        = @"\uf14d",
  .md_screen_rotation             = @"\uf14e",
  .md_sd_storage                  = @"\uf14f",
  .md_settings_system_daydream    = @"\uf150",
  .md_signal_cellular_0_bar       = @"\uf151",
  .md_signal_cellular_1_bar       = @"\uf152",
  .md_signal_cellular_2_bar       = @"\uf153",
  .md_signal_cellular_3_bar       = @"\uf154",
  .md_signal_cellular_4_bar       = @"\uf155",
  .md_signal_cellular_connected_no_internet_0_bar = @"\uf156",
  .md_signal_cellular_connected_no_internet_1_bar = @"\uf157",
  .md_signal_cellular_connected_no_internet_2_bar = @"\uf158",
  .md_signal_cellular_connected_no_internet_3_bar = @"\uf159",
  .md_signal_cellular_connected_no_internet_4_bar = @"\uf15a",
  .md_signal_cellular_no_sim      = @"\uf15b",
  .md_signal_cellular_null        = @"\uf15c",
  .md_signal_cellular_off         = @"\uf15d",
  .md_signal_wifi_0_bar           = @"\uf15e",
  .md_signal_wifi_1_bar           = @"\uf15f",
  .md_signal_wifi_2_bar           = @"\uf160",
  .md_signal_wifi_3_bar           = @"\uf161",
  .md_signal_wifi_4_bar           = @"\uf162",
  .md_signal_wifi_off             = @"\uf163",
  .md_storage                     = @"\uf164",
  .md_usb                         = @"\uf165",
  .md_wifi_lock                   = @"\uf166",
  .md_wifi_tethering              = @"\uf167",
  .md_attach_file                 = @"\uf168",
  .md_attach_money                = @"\uf169",
  .md_border_all                  = @"\uf16a",
  .md_border_bottom               = @"\uf16b",
  .md_border_clear                = @"\uf16c",
  .md_border_color                = @"\uf16d",
  .md_border_horizontal           = @"\uf16e",
  .md_border_inner                = @"\uf16f",
  .md_border_left                 = @"\uf170",
  .md_border_outer                = @"\uf171",
  .md_border_right                = @"\uf172",
  .md_border_style                = @"\uf173",
  .md_border_top                  = @"\uf174",
  .md_border_vertical             = @"\uf175",
  .md_format_align_center         = @"\uf176",
  .md_format_align_justify        = @"\uf177",
  .md_format_align_left           = @"\uf178",
  .md_format_align_right          = @"\uf179",
  .md_format_bold                 = @"\uf17a",
  .md_format_clear                = @"\uf17b",
  .md_format_color_fill           = @"\uf17c",
  .md_format_color_reset          = @"\uf17d",
  .md_format_color_text           = @"\uf17e",
  .md_format_indent_decrease      = @"\uf17f",
  .md_format_indent_increase      = @"\uf180",
  .md_format_italic               = @"\uf181",
  .md_format_line_spacing         = @"\uf182",
  .md_format_list_bulleted        = @"\uf183",
  .md_format_list_numbered        = @"\uf184",
  .md_format_paint                = @"\uf185",
  .md_format_quote                = @"\uf186",
  .md_format_size                 = @"\uf187",
  .md_format_strikethrough        = @"\uf188",
  .md_format_textdirection_l_to_r = @"\uf189",
  .md_format_textdirection_r_to_l = @"\uf18a",
  .md_format_underline            = @"\uf18b",
  .md_functions                   = @"\uf18c",
  .md_insert_chart                = @"\uf18d",
  .md_insert_comment              = @"\uf18e",
  .md_insert_drive_file           = @"\uf18f",
  .md_insert_emoticon             = @"\uf190",
  .md_insert_invitation           = @"\uf191",
  .md_insert_link                 = @"\uf192",
  .md_insert_photo                = @"\uf193",
  .md_merge_type                  = @"\uf194",
  .md_mode_comment                = @"\uf195",
  .md_mode_edit                   = @"\uf196",
  .md_publish                     = @"\uf197",
  .md_vertical_align_bottom       = @"\uf198",
  .md_vertical_align_center       = @"\uf199",
  .md_vertical_align_top          = @"\uf19a",
  .md_wrap_text                   = @"\uf19b",
  .md_attachment                  = @"\uf19c",
  .md_cloud                       = @"\uf19d",
  .md_cloud_circle                = @"\uf19e",
  .md_cloud_done                  = @"\uf19f",
  .md_cloud_download              = @"\uf1a0",
  .md_cloud_off                   = @"\uf1a1",
  .md_cloud_queue                 = @"\uf1a2",
  .md_cloud_upload                = @"\uf1a3",
  .md_file_download               = @"\uf1a4",
  .md_file_upload                 = @"\uf1a5",
  .md_folder                      = @"\uf1a6",
  .md_folder_open                 = @"\uf1a7",
  .md_folder_shared               = @"\uf1a8",
  .md_cast                        = @"\uf1a9",
  .md_cast_connected              = @"\uf1aa",
  .md_computer                    = @"\uf1ab",
  .md_desktop_mac                 = @"\uf1ac",
  .md_desktop_windows             = @"\uf1ad",
  .md_dock                        = @"\uf1ae",
  .md_gamepad                     = @"\uf1af",
  .md_headset                     = @"\uf1b0",
  .md_headset_mic                 = @"\uf1b1",
  .md_keyboard                    = @"\uf1b2",
  .md_keyboard_alt                = @"\uf1b3",
  .md_keyboard_arrow_down         = @"\uf1b4",
  .md_keyboard_arrow_left         = @"\uf1b5",
  .md_keyboard_arrow_right        = @"\uf1b6",
  .md_keyboard_arrow_up           = @"\uf1b7",
  .md_keyboard_backspace          = @"\uf1b8",
  .md_keyboard_capslock           = @"\uf1b9",
  .md_keyboard_control            = @"\uf1ba",
  .md_keyboard_hide               = @"\uf1bb",
  .md_keyboard_return             = @"\ufc1b",
  .md_keyboard_tab                = @"\uf1bd",
  .md_keyboard_voice              = @"\uf1be",
  .md_laptop                      = @"\uf1bf",
  .md_laptop_chromebook           = @"\uf1c0",
  .md_laptop_mac                  = @"\uf1c1",
  .md_laptop_windows              = @"\uf1c2",
  .md_memory                      = @"\uf1c3",
  .md_mouse                       = @"\uf1c4",
  .md_phone_android               = @"\uf1c5",
  .md_phone_iphone                = @"\uf1c6",
  .md_phonelink                   = @"\uf1c7",
  .md_phonelink_off               = @"\uf1c8",
  .md_security                    = @"\uf1c9",
  .md_sim_card                    = @"\uf1ca",
  .md_smartphone                  = @"\uf1cb",
  .md_speaker                     = @"\uf1cc",
  .md_tablet                      = @"\uf1cd",
  .md_tablet_android              = @"\uf1ce",
  .md_tablet_mac                  = @"\uf1cf",
  .md_tv                          = @"\uf1d0",
  .md_watch                       = @"\uf1d1",
  .md_add_to_photos               = @"\uf1d2",
  .md_adjust                      = @"\uf1d3",
  .md_assistant_photo             = @"\uf1d4",
  .md_audiotrack                  = @"\uf1d5",
  .md_blur_circular               = @"\uf1d6",
  .md_blur_linear                 = @"\uf1d7",
  .md_blur_off                    = @"\uf1d8",
  .md_blur_on                     = @"\uf1d9",
  .md_brightness_1                = @"\uf1da",
  .md_brightness_2                = @"\uf1db",
  .md_brightness_3                = @"\uf1dc",
  .md_brightness_4                = @"\uf1dd",
  .md_brightness_5                = @"\uf1de",
  .md_brightness_6                = @"\uf1df",
  .md_brightness_7                = @"\uf1e0",
  .md_brush                       = @"\uf1e1",
  .md_camera                      = @"\uf1e2",
  .md_camera_alt                  = @"\uf1e3",
  .md_camera_front                = @"\uf1e4",
  .md_camera_rear                 = @"\uf1e5",
  .md_camera_roll                 = @"\uf1e6",
  .md_center_focus_strong         = @"\uf1e7",
  .md_center_focus_weak           = @"\uf1e8",
  .md_collections                 = @"\uf1e9",
  .md_colorize                    = @"\uf1ea",
  .md_color_lens                  = @"\uf1eb",
  .md_compare                     = @"\uf1ec",
  .md_control_point               = @"\uf1ed",
  .md_control_point_duplicate     = @"\uf1ee",
  .md_crop                        = @"\uf1ef",
  .md_crop_3_2                    = @"\uf1f0",
  .md_crop_5_4                    = @"\uf1f1",
  .md_crop_7_5                    = @"\uf1f2",
  .md_crop_16_9                   = @"\uf1f3",
  .md_crop_din                    = @"\uf1f4",
  .md_crop_free                   = @"\uf1f5",
  .md_crop_landscape              = @"\uf1f6",
  .md_crop_original               = @"\uf1f7",
  .md_crop_portrait               = @"\uf1f8",
  .md_crop_square                 = @"\uf1f9",
  .md_dehaze                      = @"\uf1fa",
  .md_details                     = @"\uf1fb",
  .md_edit                        = @"\uf1fc",
  .md_exposure                    = @"\uf1fd",
  .md_exposure_minus_1            = @"\uf1fe",
  .md_exposure_minus_2            = @"\uf1ff",
  .md_exposure_zero               = @"\uf100",
  .md_exposure_plus_1             = @"\uf201",
  .md_exposure_plus_2             = @"\uf202",
  .md_filter                      = @"\uf203",
  .md_filter_1                    = @"\uf204",
  .md_filter_2                    = @"\uf205",
  .md_filter_3                    = @"\uf206",
  .md_filter_4                    = @"\uf207",
  .md_filter_5                    = @"\uf208",
  .md_filter_6                    = @"\uf209",
  .md_filter_7                    = @"\uf20a",
  .md_filter_8                    = @"\uf20b",
  .md_filter_9                    = @"\uf20c",
  .md_filter_9_plus               = @"\uf20d",
  .md_filter_b_and_w              = @"\uf20e",
  .md_filter_center_focus         = @"\uf20f",
  .md_filter_drama                = @"\uf210",
  .md_filter_frames               = @"\uf211",
  .md_filter_hdr                  = @"\uf212",
  .md_filter_none                 = @"\uf213",
  .md_filter_tilt_shift           = @"\uf214",
  .md_filter_vintage              = @"\uf215",
  .md_flare                       = @"\uf216",
  .md_flash_auto                  = @"\uf217",
  .md_flash_off                   = @"\uf218",
  .md_flash_on                    = @"\uf219",
  .md_flip                        = @"\uf21a",
  .md_gradient                    = @"\uf21b",
  .md_grain                       = @"\uf21c",
  .md_grid_off                    = @"\uf21d",
  .md_grid_on                     = @"\uf21e",
  .md_hdr_off                     = @"\uf21f",
  .md_hdr_on                      = @"\uf220",
  .md_hdr_strong                  = @"\uf221",
  .md_hdr_weak                    = @"\uf222",
  .md_healing                     = @"\uf223",
  .md_image                       = @"\uf224",
  .md_image_aspect_ratio          = @"\uf225",
  .md_iso                         = @"\uf226",
  .md_landscape                   = @"\uf227",
  .md_leak_add                    = @"\uf228",
  .md_leak_remove                 = @"\uf229",
  .md_lens                        = @"\uf22a",
  .md_looks                       = @"\uf22b",
  .md_looks_1                     = @"\ufc22",
  .md_looks_2                     = @"\uf22d",
  .md_looks_3                     = @"\uf22e",
  .md_looks_4                     = @"\uf22f",
  .md_looks_5                     = @"\uf230",
  .md_looks_6                     = @"\uf231",
  .md_loupe                       = @"\uf232",
  .md_movie_creation              = @"\uf233",
  .md_nature                      = @"\uf234",
  .md_nature_people               = @"\uf235",
  .md_navigate_before             = @"\uf236",
  .md_navigate_next               = @"\uf237",
  .md_palette                     = @"\uf238",
  .md_panorama                    = @"\uf239",
  .md_panorama_fisheye            = @"\uf23a",
  .md_panorama_horizontal         = @"\uf23b",
  .md_panorama_vertical           = @"\uf23c",
  .md_panorama_wide_angle         = @"\uf23d",
  .md_photo                       = @"\uf23e",
  .md_photo_album                 = @"\uf23f",
  .md_photo_camera                = @"\uf240",
  .md_photo_library               = @"\uf241",
  .md_portrait                    = @"\uf242",
  .md_remove_red_eye              = @"\uf243",
  .md_rotate_left                 = @"\uf244",
  .md_rotate_right                = @"\uf245",
  .md_slideshow                   = @"\uf246",
  .md_straighten                  = @"\uf247",
  .md_style                       = @"\uf248",
  .md_switch_camera               = @"\uf249",
  .md_switch_video                = @"\uf24a",
  .md_tag_faces                   = @"\uf24b",
  .md_texture                     = @"\uf24c",
  .md_timelapse                   = @"\uf24d",
  .md_timer                       = @"\uf24e",
  .md_timer_3                     = @"\uf24f",
  .md_timer_10                    = @"\uf250",
  .md_timer_auto                  = @"\uf251",
  .md_timer_off                   = @"\uf252",
  .md_tonality                    = @"\uf253",
  .md_transform                   = @"\uf254",
  .md_tune                        = @"\uf255",
  .md_wb_auto                     = @"\uf256",
  .md_wb_cloudy                   = @"\uf257",
  .md_wb_incandescent             = @"\uf258",
  .md_wb_irradescent              = @"\uf259",
  .md_wb_sunny                    = @"\uf25a",
  .md_beenhere                    = @"\uf25b",
  .md_directions                  = @"\ufc25",
  .md_directions_bike             = @"\uf25d",
  .md_directions_bus              = @"\uf25e",
  .md_directions_car              = @"\uf25f",
  .md_directions_ferry            = @"\uf260",
  .md_directions_subway           = @"\uf261",
  .md_directions_train            = @"\uf262",
  .md_directions_transit          = @"\uf263",
  .md_directions_walk             = @"\uf264",
  .md_flight                      = @"\uf265",
  .md_hotel                       = @"\uf266",
  .md_layers                      = @"\uf267",
  .md_layers_clear                = @"\uf268",
  .md_local_airport               = @"\uf269",
  .md_local_atm                   = @"\uf26a",
  .md_local_attraction            = @"\uf26b",
  .md_local_bar                   = @"\uf26c",
  .md_local_cafe                  = @"\uf26d",
  .md_local_car_wash              = @"\uf26e",
  .md_local_convenience_store     = @"\uf26f",
  .md_local_drink                 = @"\uf270",
  .md_local_florist               = @"\uf271",
  .md_local_gas_station           = @"\uf272",
  .md_local_grocery_store         = @"\uf273",
  .md_local_hospital              = @"\uf274",
  .md_local_hotel                 = @"\uf275",
  .md_local_laundry_service       = @"\uf276",
  .md_local_library               = @"\uf277",
  .md_local_mall                  = @"\uf278",
  .md_local_movies                = @"\uf279",
  .md_local_offer                 = @"\uf27a",
  .md_local_parking               = @"\uf27b",
  .md_local_pharmacy              = @"\uf27c",
  .md_local_phone                 = @"\uf27d",
  .md_local_pizza                 = @"\uf27e",
  .md_local_play                  = @"\uf27f",
  .md_local_post_office           = @"\uf280",
  .md_local_print_shop            = @"\uf281",
  .md_local_restaurant            = @"\uf282",
  .md_local_see                   = @"\uf283",
  .md_local_shipping              = @"\uf284",
  .md_local_taxi                  = @"\uf285",
  .md_location_history            = @"\uf286",
  .md_map                         = @"\uf287",
  .md_my_location                 = @"\uf288",
  .md_navigation                  = @"\uf289",
  .md_pin_drop                    = @"\uf28a",
  .md_place                       = @"\uf28b",
  .md_rate_review                 = @"\uf28c",
  .md_restaurant_menu             = @"\uf28d",
  .md_satellite                   = @"\uf28e",
  .md_store_mall_directory        = @"\uf28f",
  .md_terrain                     = @"\uf290",
  .md_traffic                     = @"\uf291",
  .md_apps                        = @"\uf292",
  .md_cancel                      = @"\uf293",
  .md_arrow_drop_down_circle      = @"\uf294",
  .md_arrow_drop_down             = @"\uf295",
  .md_arrow_drop_up               = @"\uf296",
  .md_arrow_back                  = @"\uf297",
  .md_arrow_forward               = @"\uf298",
  .md_check                       = @"\uf299",
  .md_close                       = @"\uf29a",
  .md_chevron_left                = @"\uf29b",
  .md_chevron_right               = @"\ufc29",
  .md_expand_less                 = @"\uf29d",
  .md_expand_more                 = @"\uf29e",
  .md_fullscreen                  = @"\uf29f",
  .md_fullscreen_exit             = @"\uf2a0",
  .md_menu                        = @"\uf2a1",
  .md_more_horiz                  = @"\uf2a2",
  .md_more_vert                   = @"\uf2a3",
  .md_refresh                     = @"\uf2a4",
  .md_unfold_less                 = @"\uf2a5",
  .md_unfold_more                 = @"\uf2a6",
  .md_adb                         = @"\uf2a7",
  .md_bluetooth_audio             = @"\uf2a8",
  .md_disc_full                   = @"\uf2a9",
  .md_dnd_forwardslash            = @"\uf2aa",
  .md_do_not_disturb              = @"\uf2ab",
  .md_drive_eta                   = @"\uf2ac",
  .md_event_available             = @"\uf2ad",
  .md_event_busy                  = @"\uf2ae",
  .md_event_note                  = @"\uf2af",
  .md_folder_special              = @"\uf2b0",
  .md_mms                         = @"\uf2b1",
  .md_more                        = @"\uf2b2",
  .md_network_locked              = @"\uf2b3",
  .md_phone_bluetooth_speaker     = @"\uf2b4",
  .md_phone_forwarded             = @"\uf2b5",
  .md_phone_in_talk               = @"\uf2b6",
  .md_phone_locked                = @"\uf2b7",
  .md_phone_missed                = @"\uf2b8",
  .md_phone_paused                = @"\uf2b9",
  .md_play_download               = @"\uf2ba",
  .md_play_install                = @"\uf2bb",
  .md_sd_card                     = @"\uf2bc",
  .md_sim_card_alert              = @"\uf2bd",
  .md_sms                         = @"\uf2be",
  .md_sms_failed                  = @"\uf2bf",
  .md_sync                        = @"\uf2c0",
  .md_sync_disabled               = @"\uf2c1",
  .md_sync_problem                = @"\uf2c2",
  .md_system_update               = @"\uf2c3",
  .md_tap_and_play                = @"\uf2c4",
  .md_time_to_leave               = @"\uf2c5",
  .md_vibration                   = @"\uf2c6",
  .md_voice_chat                  = @"\uf2c7",
  .md_vpn_lock                    = @"\uf2c8",
  .md_cake                        = @"\uf2c9",
  .md_domain                      = @"\uf2ca",
  .md_location_city               = @"\uf2cb",
  .md_mood                        = @"\uf2cc",
  .md_notifications_none          = @"\uf2cd",
  .md_notifications               = @"\uf2ce",
  .md_notifications_off           = @"\uf2cf",
  .md_notifications_on            = @"\uf2d0",
  .md_notifications_paused        = @"\uf2d1",
  .md_pages                       = @"\uf2d2",
  .md_party_mode                  = @"\uf2d3",
  .md_group                       = @"\uf2d4",
  .md_group_add                   = @"\uf2d5",
  .md_people                      = @"\uf2d6",
  .md_people_outline              = @"\uf2d7",
  .md_person                      = @"\uf2d8",
  .md_person_add                  = @"\uf2d9",
  .md_person_outline              = @"\uf2da",
  .md_plus_one                    = @"\uf2db",
  .md_poll                        = @"\uf2dc",
  .md_public                      = @"\uf2dd",
  .md_school                      = @"\uf2de",
  .md_share                       = @"\uf2df",
  .md_whatshot                    = @"\uf2e0",
  .md_check_box                   = @"\uf2e1",
  .md_check_box_outline_blank     = @"\uf2e2",
  .md_radio_button_off            = @"\uf2e3",
  .md_radio_button_on             = @"\uf2e4",
  .md_star                        = @"\uf2e5",
  .md_star_half                   = @"\uf2e6",
  .md_star_outline                = @"\uf2e7",
};

@interface VCMaterialDesignIcons ()

@property (strong, nonatomic) NSMutableAttributedString *iconAttributedString;

@property (nonatomic) CGFloat fontSize;

@end

@implementation VCMaterialDesignIcons

+ (void)initialize {
  if (self == VCMaterialDesignIcons.class) {
    NSURL *url = [[NSBundle bundleForClass:self] URLForResource:@"Material-Design-Iconic-Font" withExtension:@"ttf"];
    NSAssert([[NSFileManager defaultManager] fileExistsAtPath:[url path]], @"Font file doesn't exist");

    CGDataProviderRef fontDataProvider = CGDataProviderCreateWithURL((__bridge CFURLRef)url);
    CGFontRef newFont = CGFontCreateWithDataProvider(fontDataProvider);
    CGDataProviderRelease(fontDataProvider);

    CFErrorRef error;
    CTFontManagerRegisterGraphicsFont(newFont, &error);
    CGFontRelease(newFont);
  }
}

+ (instancetype)iconWithCode:(NSString *)code fontSize:(CGFloat)fontSize {
  VCMaterialDesignIcons *icon = [VCMaterialDesignIcons new];
  icon.fontSize = fontSize;
  icon.iconAttributedString = [NSMutableAttributedString.alloc initWithString:code
                                                                   attributes:@{NSFontAttributeName: [self iconFontWithSize:fontSize]}];
  return icon;
}

+ (UIFont *)iconFontWithSize:(CGFloat)size {
  UIFont *font = [UIFont fontWithName:@"Material-Design-Iconic-Font" size:size];
  NSAssert(font, @"Should not be nil, check if file is added to the application bundle");
  return font;
}

- (UIImage *)imageWithSize:(CGSize)imageSize {
  UIGraphicsBeginImageContextWithOptions(imageSize, NO, 0.0);

  [self.iconAttributedString drawInRect:({
    CGSize iconSize = [self.iconAttributedString size];
    CGFloat xOffset = (imageSize.width - iconSize.width) / 2.0;
    CGFloat yOffset = (imageSize.height - iconSize.height) / 2.0;
    CGRectMake(xOffset, yOffset, iconSize.width, iconSize.height);
  })];

  UIImage *iconImage = UIGraphicsGetImageFromCurrentImageContext();

  UIGraphicsEndImageContext();
  return iconImage;
}

- (UIImage *)image {
  return [self imageWithSize:CGSizeMake(self.fontSize, self.fontSize)];
}

- (void)addAttributes:(NSDictionary *)attributes {
  [self.iconAttributedString addAttributes:attributes range:[self rangeForAttributedText]];
}

- (void)addAttribute:(NSString *)name value:(id)value {
  [self.iconAttributedString addAttribute:name value:value range:[self rangeForAttributedText]];
}

- (void)removeAttribute:(NSString *)name {
  [self.iconAttributedString removeAttribute:name range:[self rangeForAttributedText]];
}

- (id)attribute:(NSString *)attrName {
  return [self.iconAttributedString attributesAtIndex:0 effectiveRange:NULL];
}

- (NSRange)rangeForAttributedText {
  return NSMakeRange(0, [self.iconAttributedString length]);
}

+ (NSArray *)allIcons {
  return @[
    VCMaterialDesignIconCode.md_3d_rotation                 ,
    VCMaterialDesignIconCode.md_accessibility               ,
    VCMaterialDesignIconCode.md_account_balance             ,
    VCMaterialDesignIconCode.md_account_balance_wallet      ,
    VCMaterialDesignIconCode.md_account_box                 ,
    VCMaterialDesignIconCode.md_account_child               ,
    VCMaterialDesignIconCode.md_account_circle              ,
    VCMaterialDesignIconCode.md_add_shopping_cart           ,
    VCMaterialDesignIconCode.md_alarm                       ,
    VCMaterialDesignIconCode.md_alarm_add                   ,
    VCMaterialDesignIconCode.md_alarm_off                   ,
    VCMaterialDesignIconCode.md_alarm_on                    ,
    VCMaterialDesignIconCode.md_android                     ,
    VCMaterialDesignIconCode.md_announcement                ,
    VCMaterialDesignIconCode.md_aspect_ratio                ,
    VCMaterialDesignIconCode.md_assessment                  ,
    VCMaterialDesignIconCode.md_assignment                  ,
    VCMaterialDesignIconCode.md_assignment_ind              ,
    VCMaterialDesignIconCode.md_assignment_late             ,
    VCMaterialDesignIconCode.md_assignment_return           ,
    VCMaterialDesignIconCode.md_assignment_returned         ,
    VCMaterialDesignIconCode.md_assignment_turned_in        ,
    VCMaterialDesignIconCode.md_autorenew                   ,
    VCMaterialDesignIconCode.md_backup                      ,
    VCMaterialDesignIconCode.md_book                        ,
    VCMaterialDesignIconCode.md_bookmark                    ,
    VCMaterialDesignIconCode.md_bookmark_outline            ,
    VCMaterialDesignIconCode.md_bug_report                  ,
    VCMaterialDesignIconCode.md_cached                      ,
    VCMaterialDesignIconCode.md_class                       ,
    VCMaterialDesignIconCode.md_credit_card                 ,
    VCMaterialDesignIconCode.md_dashboard                   ,
    VCMaterialDesignIconCode.md_delete                      ,
    VCMaterialDesignIconCode.md_description                 ,
    VCMaterialDesignIconCode.md_dns                         ,
    VCMaterialDesignIconCode.md_done                        ,
    VCMaterialDesignIconCode.md_done_all                    ,
    VCMaterialDesignIconCode.md_event                       ,
    VCMaterialDesignIconCode.md_exit_to_app                 ,
    VCMaterialDesignIconCode.md_explore                     ,
    VCMaterialDesignIconCode.md_extension                   ,
    VCMaterialDesignIconCode.md_face_unlock                 ,
    VCMaterialDesignIconCode.md_favorite                    ,
    VCMaterialDesignIconCode.md_favorite_outline            ,
    VCMaterialDesignIconCode.md_find_in_page                ,
    VCMaterialDesignIconCode.md_find_replace                ,
    VCMaterialDesignIconCode.md_flip_to_back                ,
    VCMaterialDesignIconCode.md_flip_to_front               ,
    VCMaterialDesignIconCode.md_get_app                     ,
    VCMaterialDesignIconCode.md_grade                       ,
    VCMaterialDesignIconCode.md_group_work                  ,
    VCMaterialDesignIconCode.md_help                        ,
    VCMaterialDesignIconCode.md_highlight_remove            ,
    VCMaterialDesignIconCode.md_history                     ,
    VCMaterialDesignIconCode.md_home                        ,
    VCMaterialDesignIconCode.md_https                       ,
    VCMaterialDesignIconCode.md_info                        ,
    VCMaterialDesignIconCode.md_info_outline                ,
    VCMaterialDesignIconCode.md_input                       ,
    VCMaterialDesignIconCode.md_invert_colors               ,
    VCMaterialDesignIconCode.md_label                       ,
    VCMaterialDesignIconCode.md_label_outline               ,
    VCMaterialDesignIconCode.md_language                    ,
    VCMaterialDesignIconCode.md_launch                      ,
    VCMaterialDesignIconCode.md_list                        ,
    VCMaterialDesignIconCode.md_lock                        ,
    VCMaterialDesignIconCode.md_lock_open                   ,
    VCMaterialDesignIconCode.md_lock_outline                ,
    VCMaterialDesignIconCode.md_loyalty                     ,
    VCMaterialDesignIconCode.md_markunread_mailbox          ,
    VCMaterialDesignIconCode.md_note_add                    ,
    VCMaterialDesignIconCode.md_open_in_browser             ,
    VCMaterialDesignIconCode.md_open_in_new                 ,
    VCMaterialDesignIconCode.md_open_with                   ,
    VCMaterialDesignIconCode.md_pageview                    ,
    VCMaterialDesignIconCode.md_payment                     ,
    VCMaterialDesignIconCode.md_perm_camera_mic             ,
    VCMaterialDesignIconCode.md_perm_contact_cal            ,
    VCMaterialDesignIconCode.md_perm_data_setting           ,
    VCMaterialDesignIconCode.md_perm_device_info            ,
    VCMaterialDesignIconCode.md_perm_identity               ,
    VCMaterialDesignIconCode.md_perm_media                  ,
    VCMaterialDesignIconCode.md_perm_phone_msg              ,
    VCMaterialDesignIconCode.md_perm_scan_wifi              ,
    VCMaterialDesignIconCode.md_picture_in_picture          ,
    VCMaterialDesignIconCode.md_polymer                     ,
    VCMaterialDesignIconCode.md_print                       ,
    VCMaterialDesignIconCode.md_query_builder               ,
    VCMaterialDesignIconCode.md_question_answer             ,
    VCMaterialDesignIconCode.md_receipt                     ,
    VCMaterialDesignIconCode.md_redeem                      ,
    VCMaterialDesignIconCode.md_report_problem              ,
    VCMaterialDesignIconCode.md_restore                     ,
    VCMaterialDesignIconCode.md_room                        ,
    VCMaterialDesignIconCode.md_schedule                    ,
    VCMaterialDesignIconCode.md_search                      ,
    VCMaterialDesignIconCode.md_settings                    ,
    VCMaterialDesignIconCode.md_settings_applications       ,
    VCMaterialDesignIconCode.md_settings_backup_restore     ,
    VCMaterialDesignIconCode.md_settings_bluetooth          ,
    VCMaterialDesignIconCode.md_settings_cell               ,
    VCMaterialDesignIconCode.md_settings_display            ,
    VCMaterialDesignIconCode.md_settings_ethernet           ,
    VCMaterialDesignIconCode.md_settings_input_antenna      ,
    VCMaterialDesignIconCode.md_settings_input_component    ,
    VCMaterialDesignIconCode.md_settings_input_composite    ,
    VCMaterialDesignIconCode.md_settings_input_hdmi         ,
    VCMaterialDesignIconCode.md_settings_input_svideo       ,
    VCMaterialDesignIconCode.md_settings_overscan           ,
    VCMaterialDesignIconCode.md_settings_phone              ,
    VCMaterialDesignIconCode.md_settings_power              ,
    VCMaterialDesignIconCode.md_settings_remote             ,
    VCMaterialDesignIconCode.md_settings_voice              ,
    VCMaterialDesignIconCode.md_shop                        ,
    VCMaterialDesignIconCode.md_shopping_basket             ,
    VCMaterialDesignIconCode.md_shopping_cart               ,
    VCMaterialDesignIconCode.md_shop_two                    ,
    VCMaterialDesignIconCode.md_speaker_notes               ,
    VCMaterialDesignIconCode.md_spellcheck                  ,
    VCMaterialDesignIconCode.md_star_rate                   ,
    VCMaterialDesignIconCode.md_stars                       ,
    VCMaterialDesignIconCode.md_store                       ,
    VCMaterialDesignIconCode.md_subject                     ,
    VCMaterialDesignIconCode.md_swap_horiz                  ,
    VCMaterialDesignIconCode.md_swap_vert                   ,
    VCMaterialDesignIconCode.md_swap_vert_circle            ,
    VCMaterialDesignIconCode.md_system_update_tv            ,
    VCMaterialDesignIconCode.md_tab                         ,
    VCMaterialDesignIconCode.md_tab_unselected              ,
    VCMaterialDesignIconCode.md_theaters                    ,
    VCMaterialDesignIconCode.md_thumb_down                  ,
    VCMaterialDesignIconCode.md_thumbs_up_down              ,
    VCMaterialDesignIconCode.md_thumb_up                    ,
    VCMaterialDesignIconCode.md_toc                         ,
    VCMaterialDesignIconCode.md_today                       ,
    VCMaterialDesignIconCode.md_track_changes               ,
    VCMaterialDesignIconCode.md_translate                   ,
    VCMaterialDesignIconCode.md_trending_down               ,
    VCMaterialDesignIconCode.md_trending_neutral            ,
    VCMaterialDesignIconCode.md_trending_up                 ,
    VCMaterialDesignIconCode.md_turned_in                   ,
    VCMaterialDesignIconCode.md_turned_in_not               ,
    VCMaterialDesignIconCode.md_verified_user               ,
    VCMaterialDesignIconCode.md_view_agenda                 ,
    VCMaterialDesignIconCode.md_view_array                  ,
    VCMaterialDesignIconCode.md_view_carousel               ,
    VCMaterialDesignIconCode.md_view_column                 ,
    VCMaterialDesignIconCode.md_view_day                    ,
    VCMaterialDesignIconCode.md_view_headline               ,
    VCMaterialDesignIconCode.md_view_list                   ,
    VCMaterialDesignIconCode.md_view_module                 ,
    VCMaterialDesignIconCode.md_view_quilt                  ,
    VCMaterialDesignIconCode.md_view_stream                 ,
    VCMaterialDesignIconCode.md_view_week                   ,
    VCMaterialDesignIconCode.md_visibility                  ,
    VCMaterialDesignIconCode.md_visibility_off              ,
    VCMaterialDesignIconCode.md_wallet_giftcard             ,
    VCMaterialDesignIconCode.md_wallet_membership           ,
    VCMaterialDesignIconCode.md_wallet_travel               ,
    VCMaterialDesignIconCode.md_work                        ,
    VCMaterialDesignIconCode.md_error                       ,
    VCMaterialDesignIconCode.md_warning                     ,
    VCMaterialDesignIconCode.md_album                       ,
    VCMaterialDesignIconCode.md_av_timer                    ,
    VCMaterialDesignIconCode.md_closed_caption              ,
    VCMaterialDesignIconCode.md_equalizer                   ,
    VCMaterialDesignIconCode.md_explicit                    ,
    VCMaterialDesignIconCode.md_fast_forward                ,
    VCMaterialDesignIconCode.md_fast_rewind                 ,
    VCMaterialDesignIconCode.md_games                       ,
    VCMaterialDesignIconCode.md_hearing                     ,
    VCMaterialDesignIconCode.md_high_quality                ,
    VCMaterialDesignIconCode.md_loop                        ,
    VCMaterialDesignIconCode.md_mic                         ,
    VCMaterialDesignIconCode.md_mic_none                    ,
    VCMaterialDesignIconCode.md_mic_off                     ,
    VCMaterialDesignIconCode.md_movie                       ,
    VCMaterialDesignIconCode.md_my_library_add              ,
    VCMaterialDesignIconCode.md_my_library_books            ,
    VCMaterialDesignIconCode.md_my_library_music            ,
    VCMaterialDesignIconCode.md_new_releases                ,
    VCMaterialDesignIconCode.md_not_interested              ,
    VCMaterialDesignIconCode.md_pause                       ,
    VCMaterialDesignIconCode.md_pause_circle_fill           ,
    VCMaterialDesignIconCode.md_pause_circle_outline        ,
    VCMaterialDesignIconCode.md_play_arrow                  ,
    VCMaterialDesignIconCode.md_play_circle_fill            ,
    VCMaterialDesignIconCode.md_play_circle_outline         ,
    VCMaterialDesignIconCode.md_playlist_add                ,
    VCMaterialDesignIconCode.md_play_shopping_bag           ,
    VCMaterialDesignIconCode.md_queue                       ,
    VCMaterialDesignIconCode.md_queue_music                 ,
    VCMaterialDesignIconCode.md_radio                       ,
    VCMaterialDesignIconCode.md_recent_actors               ,
    VCMaterialDesignIconCode.md_repeat                      ,
    VCMaterialDesignIconCode.md_repeat_one                  ,
    VCMaterialDesignIconCode.md_replay                      ,
    VCMaterialDesignIconCode.md_shuffle                     ,
    VCMaterialDesignIconCode.md_skip_next                   ,
    VCMaterialDesignIconCode.md_skip_previous               ,
    VCMaterialDesignIconCode.md_snooze                      ,
    VCMaterialDesignIconCode.md_stop                        ,
    VCMaterialDesignIconCode.md_subtitles                   ,
    VCMaterialDesignIconCode.md_surround_sound              ,
    VCMaterialDesignIconCode.md_videocam                    ,
    VCMaterialDesignIconCode.md_videocam_off                ,
    VCMaterialDesignIconCode.md_video_collection            ,
    VCMaterialDesignIconCode.md_volume_down                 ,
    VCMaterialDesignIconCode.md_volume_mute                 ,
    VCMaterialDesignIconCode.md_volume_off                  ,
    VCMaterialDesignIconCode.md_volume_up                   ,
    VCMaterialDesignIconCode.md_web                         ,
    VCMaterialDesignIconCode.md_business                    ,
    VCMaterialDesignIconCode.md_call                        ,
    VCMaterialDesignIconCode.md_call_end                    ,
    VCMaterialDesignIconCode.md_call_made                   ,
    VCMaterialDesignIconCode.md_call_merge                  ,
    VCMaterialDesignIconCode.md_call_missed                 ,
    VCMaterialDesignIconCode.md_call_received               ,
    VCMaterialDesignIconCode.md_call_split                  ,
    VCMaterialDesignIconCode.md_chat                        ,
    VCMaterialDesignIconCode.md_clear_all                   ,
    VCMaterialDesignIconCode.md_comment                     ,
    VCMaterialDesignIconCode.md_contacts                    ,
    VCMaterialDesignIconCode.md_dialer_sip                  ,
    VCMaterialDesignIconCode.md_dialpad                     ,
    VCMaterialDesignIconCode.md_dnd_on                      ,
    VCMaterialDesignIconCode.md_email                       ,
    VCMaterialDesignIconCode.md_forum                       ,
    VCMaterialDesignIconCode.md_import_export               ,
    VCMaterialDesignIconCode.md_invert_colors_off           ,
    VCMaterialDesignIconCode.md_invert_colors_on            ,
    VCMaterialDesignIconCode.md_live_help                   ,
    VCMaterialDesignIconCode.md_location_off                ,
    VCMaterialDesignIconCode.md_location_on                 ,
    VCMaterialDesignIconCode.md_message                     ,
    VCMaterialDesignIconCode.md_messenger                   ,
    VCMaterialDesignIconCode.md_no_sim                      ,
    VCMaterialDesignIconCode.md_phone                       ,
    VCMaterialDesignIconCode.md_portable_wifi_off           ,
    VCMaterialDesignIconCode.md_quick_contacts_dialer       ,
    VCMaterialDesignIconCode.md_quick_contacts_mail         ,
    VCMaterialDesignIconCode.md_ring_volume                 ,
    VCMaterialDesignIconCode.md_stay_current_landscape      ,
    VCMaterialDesignIconCode.md_stay_current_portrait       ,
    VCMaterialDesignIconCode.md_stay_primary_landscape      ,
    VCMaterialDesignIconCode.md_stay_primary_portrait       ,
    VCMaterialDesignIconCode.md_swap_calls                  ,
    VCMaterialDesignIconCode.md_textsms                     ,
    VCMaterialDesignIconCode.md_voicemail                   ,
    VCMaterialDesignIconCode.md_vpn_key                     ,
    VCMaterialDesignIconCode.md_add                         ,
    VCMaterialDesignIconCode.md_add_box                     ,
    VCMaterialDesignIconCode.md_add_circle                  ,
    VCMaterialDesignIconCode.md_add_circle_outline          ,
    VCMaterialDesignIconCode.md_archive                     ,
    VCMaterialDesignIconCode.md_backspace                   ,
    VCMaterialDesignIconCode.md_block                       ,
    VCMaterialDesignIconCode.md_clear                       ,
    VCMaterialDesignIconCode.md_content_copy                ,
    VCMaterialDesignIconCode.md_content_cut                 ,
    VCMaterialDesignIconCode.md_content_paste               ,
    VCMaterialDesignIconCode.md_create                      ,
    VCMaterialDesignIconCode.md_drafts                      ,
    VCMaterialDesignIconCode.md_filter_list                 ,
    VCMaterialDesignIconCode.md_flag                        ,
    VCMaterialDesignIconCode.md_forward                     ,
    VCMaterialDesignIconCode.md_gesture                     ,
    VCMaterialDesignIconCode.md_inbox                       ,
    VCMaterialDesignIconCode.md_link                        ,
    VCMaterialDesignIconCode.md_mail                        ,
    VCMaterialDesignIconCode.md_markunread                  ,
    VCMaterialDesignIconCode.md_redo                        ,
    VCMaterialDesignIconCode.md_remove                      ,
    VCMaterialDesignIconCode.md_remove_circle               ,
    VCMaterialDesignIconCode.md_remove_circle_outline       ,
    VCMaterialDesignIconCode.md_reply                       ,
    VCMaterialDesignIconCode.md_reply_all                   ,
    VCMaterialDesignIconCode.md_report                      ,
    VCMaterialDesignIconCode.md_save                        ,
    VCMaterialDesignIconCode.md_select_all                  ,
    VCMaterialDesignIconCode.md_send                        ,
    VCMaterialDesignIconCode.md_sort                        ,
    VCMaterialDesignIconCode.md_text_format                 ,
    VCMaterialDesignIconCode.md_undo                        ,
    VCMaterialDesignIconCode.md_access_alarm                ,
    VCMaterialDesignIconCode.md_access_alarms               ,
    VCMaterialDesignIconCode.md_access_time                 ,
    VCMaterialDesignIconCode.md_add_alarm                   ,
    VCMaterialDesignIconCode.md_airplanemode_off            ,
    VCMaterialDesignIconCode.md_airplanemode_on             ,
    VCMaterialDesignIconCode.md_battery_20                  ,
    VCMaterialDesignIconCode.md_battery_30                  ,
    VCMaterialDesignIconCode.md_battery_50                  ,
    VCMaterialDesignIconCode.md_battery_60                  ,
    VCMaterialDesignIconCode.md_battery_80                  ,
    VCMaterialDesignIconCode.md_battery_90                  ,
    VCMaterialDesignIconCode.md_battery_alert               ,
    VCMaterialDesignIconCode.md_battery_charging_20         ,
    VCMaterialDesignIconCode.md_battery_charging_30         ,
    VCMaterialDesignIconCode.md_battery_charging_50         ,
    VCMaterialDesignIconCode.md_battery_charging_60         ,
    VCMaterialDesignIconCode.md_battery_charging_80         ,
    VCMaterialDesignIconCode.md_battery_charging_90         ,
    VCMaterialDesignIconCode.md_battery_charging_full       ,
    VCMaterialDesignIconCode.md_battery_full                ,
    VCMaterialDesignIconCode.md_battery_std                 ,
    VCMaterialDesignIconCode.md_battery_unknown             ,
    VCMaterialDesignIconCode.md_bluetooth                   ,
    VCMaterialDesignIconCode.md_bluetooth_connected         ,
    VCMaterialDesignIconCode.md_bluetooth_disabled          ,
    VCMaterialDesignIconCode.md_bluetooth_searching         ,
    VCMaterialDesignIconCode.md_brightness_auto             ,
    VCMaterialDesignIconCode.md_brightness_high             ,
    VCMaterialDesignIconCode.md_brightness_low              ,
    VCMaterialDesignIconCode.md_brightness_medium           ,
    VCMaterialDesignIconCode.md_data_usage                  ,
    VCMaterialDesignIconCode.md_developer_mode              ,
    VCMaterialDesignIconCode.md_devices                     ,
    VCMaterialDesignIconCode.md_dvr                         ,
    VCMaterialDesignIconCode.md_gps_fixed                   ,
    VCMaterialDesignIconCode.md_gps_not_fixed               ,
    VCMaterialDesignIconCode.md_gps_off                     ,
    VCMaterialDesignIconCode.md_location_disabled           ,
    VCMaterialDesignIconCode.md_location_searching          ,
    VCMaterialDesignIconCode.md_multitrack_audio            ,
    VCMaterialDesignIconCode.md_network_cell                ,
    VCMaterialDesignIconCode.md_network_wifi                ,
    VCMaterialDesignIconCode.md_nfc                         ,
    VCMaterialDesignIconCode.md_now_wallpaper               ,
    VCMaterialDesignIconCode.md_now_widgets                 ,
    VCMaterialDesignIconCode.md_screen_lock_landscape       ,
    VCMaterialDesignIconCode.md_screen_lock_portrait        ,
    VCMaterialDesignIconCode.md_screen_lock_rotation        ,
    VCMaterialDesignIconCode.md_screen_rotation             ,
    VCMaterialDesignIconCode.md_sd_storage                  ,
    VCMaterialDesignIconCode.md_settings_system_daydream    ,
    VCMaterialDesignIconCode.md_signal_cellular_0_bar       ,
    VCMaterialDesignIconCode.md_signal_cellular_1_bar       ,
    VCMaterialDesignIconCode.md_signal_cellular_2_bar       ,
    VCMaterialDesignIconCode.md_signal_cellular_3_bar       ,
    VCMaterialDesignIconCode.md_signal_cellular_4_bar       ,
    VCMaterialDesignIconCode.md_signal_cellular_connected_no_internet_0_bar,
    VCMaterialDesignIconCode.md_signal_cellular_connected_no_internet_1_bar,
    VCMaterialDesignIconCode.md_signal_cellular_connected_no_internet_2_bar,
    VCMaterialDesignIconCode.md_signal_cellular_connected_no_internet_3_bar,
    VCMaterialDesignIconCode.md_signal_cellular_connected_no_internet_4_bar,
    VCMaterialDesignIconCode.md_signal_cellular_no_sim      ,
    VCMaterialDesignIconCode.md_signal_cellular_null        ,
    VCMaterialDesignIconCode.md_signal_cellular_off         ,
    VCMaterialDesignIconCode.md_signal_wifi_0_bar           ,
    VCMaterialDesignIconCode.md_signal_wifi_1_bar           ,
    VCMaterialDesignIconCode.md_signal_wifi_2_bar           ,
    VCMaterialDesignIconCode.md_signal_wifi_3_bar           ,
    VCMaterialDesignIconCode.md_signal_wifi_4_bar           ,
    VCMaterialDesignIconCode.md_signal_wifi_off             ,
    VCMaterialDesignIconCode.md_storage                     ,
    VCMaterialDesignIconCode.md_usb                         ,
    VCMaterialDesignIconCode.md_wifi_lock                   ,
    VCMaterialDesignIconCode.md_wifi_tethering              ,
    VCMaterialDesignIconCode.md_attach_file                 ,
    VCMaterialDesignIconCode.md_attach_money                ,
    VCMaterialDesignIconCode.md_border_all                  ,
    VCMaterialDesignIconCode.md_border_bottom               ,
    VCMaterialDesignIconCode.md_border_clear                ,
    VCMaterialDesignIconCode.md_border_color                ,
    VCMaterialDesignIconCode.md_border_horizontal           ,
    VCMaterialDesignIconCode.md_border_inner                ,
    VCMaterialDesignIconCode.md_border_left                 ,
    VCMaterialDesignIconCode.md_border_outer                ,
    VCMaterialDesignIconCode.md_border_right                ,
    VCMaterialDesignIconCode.md_border_style                ,
    VCMaterialDesignIconCode.md_border_top                  ,
    VCMaterialDesignIconCode.md_border_vertical             ,
    VCMaterialDesignIconCode.md_format_align_center         ,
    VCMaterialDesignIconCode.md_format_align_justify        ,
    VCMaterialDesignIconCode.md_format_align_left           ,
    VCMaterialDesignIconCode.md_format_align_right          ,
    VCMaterialDesignIconCode.md_format_bold                 ,
    VCMaterialDesignIconCode.md_format_clear                ,
    VCMaterialDesignIconCode.md_format_color_fill           ,
    VCMaterialDesignIconCode.md_format_color_reset          ,
    VCMaterialDesignIconCode.md_format_color_text           ,
    VCMaterialDesignIconCode.md_format_indent_decrease      ,
    VCMaterialDesignIconCode.md_format_indent_increase      ,
    VCMaterialDesignIconCode.md_format_italic               ,
    VCMaterialDesignIconCode.md_format_line_spacing         ,
    VCMaterialDesignIconCode.md_format_list_bulleted        ,
    VCMaterialDesignIconCode.md_format_list_numbered        ,
    VCMaterialDesignIconCode.md_format_paint                ,
    VCMaterialDesignIconCode.md_format_quote                ,
    VCMaterialDesignIconCode.md_format_size                 ,
    VCMaterialDesignIconCode.md_format_strikethrough        ,
    VCMaterialDesignIconCode.md_format_textdirection_l_to_r ,
    VCMaterialDesignIconCode.md_format_textdirection_r_to_l ,
    VCMaterialDesignIconCode.md_format_underline            ,
    VCMaterialDesignIconCode.md_functions                   ,
    VCMaterialDesignIconCode.md_insert_chart                ,
    VCMaterialDesignIconCode.md_insert_comment              ,
    VCMaterialDesignIconCode.md_insert_drive_file           ,
    VCMaterialDesignIconCode.md_insert_emoticon             ,
    VCMaterialDesignIconCode.md_insert_invitation           ,
    VCMaterialDesignIconCode.md_insert_link                 ,
    VCMaterialDesignIconCode.md_insert_photo                ,
    VCMaterialDesignIconCode.md_merge_type                  ,
    VCMaterialDesignIconCode.md_mode_comment                ,
    VCMaterialDesignIconCode.md_mode_edit                   ,
    VCMaterialDesignIconCode.md_publish                     ,
    VCMaterialDesignIconCode.md_vertical_align_bottom       ,
    VCMaterialDesignIconCode.md_vertical_align_center       ,
    VCMaterialDesignIconCode.md_vertical_align_top          ,
    VCMaterialDesignIconCode.md_wrap_text                   ,
    VCMaterialDesignIconCode.md_attachment                  ,
    VCMaterialDesignIconCode.md_cloud                       ,
    VCMaterialDesignIconCode.md_cloud_circle                ,
    VCMaterialDesignIconCode.md_cloud_done                  ,
    VCMaterialDesignIconCode.md_cloud_download              ,
    VCMaterialDesignIconCode.md_cloud_off                   ,
    VCMaterialDesignIconCode.md_cloud_queue                 ,
    VCMaterialDesignIconCode.md_cloud_upload                ,
    VCMaterialDesignIconCode.md_file_download               ,
    VCMaterialDesignIconCode.md_file_upload                 ,
    VCMaterialDesignIconCode.md_folder                      ,
    VCMaterialDesignIconCode.md_folder_open                 ,
    VCMaterialDesignIconCode.md_folder_shared               ,
    VCMaterialDesignIconCode.md_cast                        ,
    VCMaterialDesignIconCode.md_cast_connected              ,
    VCMaterialDesignIconCode.md_computer                    ,
    VCMaterialDesignIconCode.md_desktop_mac                 ,
    VCMaterialDesignIconCode.md_desktop_windows             ,
    VCMaterialDesignIconCode.md_dock                        ,
    VCMaterialDesignIconCode.md_gamepad                     ,
    VCMaterialDesignIconCode.md_headset                     ,
    VCMaterialDesignIconCode.md_headset_mic                 ,
    VCMaterialDesignIconCode.md_keyboard                    ,
    VCMaterialDesignIconCode.md_keyboard_alt                ,
    VCMaterialDesignIconCode.md_keyboard_arrow_down         ,
    VCMaterialDesignIconCode.md_keyboard_arrow_left         ,
    VCMaterialDesignIconCode.md_keyboard_arrow_right        ,
    VCMaterialDesignIconCode.md_keyboard_arrow_up           ,
    VCMaterialDesignIconCode.md_keyboard_backspace          ,
    VCMaterialDesignIconCode.md_keyboard_capslock           ,
    VCMaterialDesignIconCode.md_keyboard_control            ,
    VCMaterialDesignIconCode.md_keyboard_hide               ,
    VCMaterialDesignIconCode.md_keyboard_return             ,
    VCMaterialDesignIconCode.md_keyboard_tab                ,
    VCMaterialDesignIconCode.md_keyboard_voice              ,
    VCMaterialDesignIconCode.md_laptop                      ,
    VCMaterialDesignIconCode.md_laptop_chromebook           ,
    VCMaterialDesignIconCode.md_laptop_mac                  ,
    VCMaterialDesignIconCode.md_laptop_windows              ,
    VCMaterialDesignIconCode.md_memory                      ,
    VCMaterialDesignIconCode.md_mouse                       ,
    VCMaterialDesignIconCode.md_phone_android               ,
    VCMaterialDesignIconCode.md_phone_iphone                ,
    VCMaterialDesignIconCode.md_phonelink                   ,
    VCMaterialDesignIconCode.md_phonelink_off               ,
    VCMaterialDesignIconCode.md_security                    ,
    VCMaterialDesignIconCode.md_sim_card                    ,
    VCMaterialDesignIconCode.md_smartphone                  ,
    VCMaterialDesignIconCode.md_speaker                     ,
    VCMaterialDesignIconCode.md_tablet                      ,
    VCMaterialDesignIconCode.md_tablet_android              ,
    VCMaterialDesignIconCode.md_tablet_mac                  ,
    VCMaterialDesignIconCode.md_tv                          ,
    VCMaterialDesignIconCode.md_watch                       ,
    VCMaterialDesignIconCode.md_add_to_photos               ,
    VCMaterialDesignIconCode.md_adjust                      ,
    VCMaterialDesignIconCode.md_assistant_photo             ,
    VCMaterialDesignIconCode.md_audiotrack                  ,
    VCMaterialDesignIconCode.md_blur_circular               ,
    VCMaterialDesignIconCode.md_blur_linear                 ,
    VCMaterialDesignIconCode.md_blur_off                    ,
    VCMaterialDesignIconCode.md_blur_on                     ,
    VCMaterialDesignIconCode.md_brightness_1                ,
    VCMaterialDesignIconCode.md_brightness_2                ,
    VCMaterialDesignIconCode.md_brightness_3                ,
    VCMaterialDesignIconCode.md_brightness_4                ,
    VCMaterialDesignIconCode.md_brightness_5                ,
    VCMaterialDesignIconCode.md_brightness_6                ,
    VCMaterialDesignIconCode.md_brightness_7                ,
    VCMaterialDesignIconCode.md_brush                       ,
    VCMaterialDesignIconCode.md_camera                      ,
    VCMaterialDesignIconCode.md_camera_alt                  ,
    VCMaterialDesignIconCode.md_camera_front                ,
    VCMaterialDesignIconCode.md_camera_rear                 ,
    VCMaterialDesignIconCode.md_camera_roll                 ,
    VCMaterialDesignIconCode.md_center_focus_strong         ,
    VCMaterialDesignIconCode.md_center_focus_weak           ,
    VCMaterialDesignIconCode.md_collections                 ,
    VCMaterialDesignIconCode.md_colorize                    ,
    VCMaterialDesignIconCode.md_color_lens                  ,
    VCMaterialDesignIconCode.md_compare                     ,
    VCMaterialDesignIconCode.md_control_point               ,
    VCMaterialDesignIconCode.md_control_point_duplicate     ,
    VCMaterialDesignIconCode.md_crop                        ,
    VCMaterialDesignIconCode.md_crop_3_2                    ,
    VCMaterialDesignIconCode.md_crop_5_4                    ,
    VCMaterialDesignIconCode.md_crop_7_5                    ,
    VCMaterialDesignIconCode.md_crop_16_9                   ,
    VCMaterialDesignIconCode.md_crop_din                    ,
    VCMaterialDesignIconCode.md_crop_free                   ,
    VCMaterialDesignIconCode.md_crop_landscape              ,
    VCMaterialDesignIconCode.md_crop_original               ,
    VCMaterialDesignIconCode.md_crop_portrait               ,
    VCMaterialDesignIconCode.md_crop_square                 ,
    VCMaterialDesignIconCode.md_dehaze                      ,
    VCMaterialDesignIconCode.md_details                     ,
    VCMaterialDesignIconCode.md_edit                        ,
    VCMaterialDesignIconCode.md_exposure                    ,
    VCMaterialDesignIconCode.md_exposure_minus_1            ,
    VCMaterialDesignIconCode.md_exposure_minus_2            ,
    VCMaterialDesignIconCode.md_exposure_zero               ,
    VCMaterialDesignIconCode.md_exposure_plus_1             ,
    VCMaterialDesignIconCode.md_exposure_plus_2             ,
    VCMaterialDesignIconCode.md_filter                      ,
    VCMaterialDesignIconCode.md_filter_1                    ,
    VCMaterialDesignIconCode.md_filter_2                    ,
    VCMaterialDesignIconCode.md_filter_3                    ,
    VCMaterialDesignIconCode.md_filter_4                    ,
    VCMaterialDesignIconCode.md_filter_5                    ,
    VCMaterialDesignIconCode.md_filter_6                    ,
    VCMaterialDesignIconCode.md_filter_7                    ,
    VCMaterialDesignIconCode.md_filter_8                    ,
    VCMaterialDesignIconCode.md_filter_9                    ,
    VCMaterialDesignIconCode.md_filter_9_plus               ,
    VCMaterialDesignIconCode.md_filter_b_and_w              ,
    VCMaterialDesignIconCode.md_filter_center_focus         ,
    VCMaterialDesignIconCode.md_filter_drama                ,
    VCMaterialDesignIconCode.md_filter_frames               ,
    VCMaterialDesignIconCode.md_filter_hdr                  ,
    VCMaterialDesignIconCode.md_filter_none                 ,
    VCMaterialDesignIconCode.md_filter_tilt_shift           ,
    VCMaterialDesignIconCode.md_filter_vintage              ,
    VCMaterialDesignIconCode.md_flare                       ,
    VCMaterialDesignIconCode.md_flash_auto                  ,
    VCMaterialDesignIconCode.md_flash_off                   ,
    VCMaterialDesignIconCode.md_flash_on                    ,
    VCMaterialDesignIconCode.md_flip                        ,
    VCMaterialDesignIconCode.md_gradient                    ,
    VCMaterialDesignIconCode.md_grain                       ,
    VCMaterialDesignIconCode.md_grid_off                    ,
    VCMaterialDesignIconCode.md_grid_on                     ,
    VCMaterialDesignIconCode.md_hdr_off                     ,
    VCMaterialDesignIconCode.md_hdr_on                      ,
    VCMaterialDesignIconCode.md_hdr_strong                  ,
    VCMaterialDesignIconCode.md_hdr_weak                    ,
    VCMaterialDesignIconCode.md_healing                     ,
    VCMaterialDesignIconCode.md_image                       ,
    VCMaterialDesignIconCode.md_image_aspect_ratio          ,
    VCMaterialDesignIconCode.md_iso                         ,
    VCMaterialDesignIconCode.md_landscape                   ,
    VCMaterialDesignIconCode.md_leak_add                    ,
    VCMaterialDesignIconCode.md_leak_remove                 ,
    VCMaterialDesignIconCode.md_lens                        ,
    VCMaterialDesignIconCode.md_looks                       ,
    VCMaterialDesignIconCode.md_looks_1                     ,
    VCMaterialDesignIconCode.md_looks_2                     ,
    VCMaterialDesignIconCode.md_looks_3                     ,
    VCMaterialDesignIconCode.md_looks_4                     ,
    VCMaterialDesignIconCode.md_looks_5                     ,
    VCMaterialDesignIconCode.md_looks_6                     ,
    VCMaterialDesignIconCode.md_loupe                       ,
    VCMaterialDesignIconCode.md_movie_creation              ,
    VCMaterialDesignIconCode.md_nature                      ,
    VCMaterialDesignIconCode.md_nature_people               ,
    VCMaterialDesignIconCode.md_navigate_before             ,
    VCMaterialDesignIconCode.md_navigate_next               ,
    VCMaterialDesignIconCode.md_palette                     ,
    VCMaterialDesignIconCode.md_panorama                    ,
    VCMaterialDesignIconCode.md_panorama_fisheye            ,
    VCMaterialDesignIconCode.md_panorama_horizontal         ,
    VCMaterialDesignIconCode.md_panorama_vertical           ,
    VCMaterialDesignIconCode.md_panorama_wide_angle         ,
    VCMaterialDesignIconCode.md_photo                       ,
    VCMaterialDesignIconCode.md_photo_album                 ,
    VCMaterialDesignIconCode.md_photo_camera                ,
    VCMaterialDesignIconCode.md_photo_library               ,
    VCMaterialDesignIconCode.md_portrait                    ,
    VCMaterialDesignIconCode.md_remove_red_eye              ,
    VCMaterialDesignIconCode.md_rotate_left                 ,
    VCMaterialDesignIconCode.md_rotate_right                ,
    VCMaterialDesignIconCode.md_slideshow                   ,
    VCMaterialDesignIconCode.md_straighten                  ,
    VCMaterialDesignIconCode.md_style                       ,
    VCMaterialDesignIconCode.md_switch_camera               ,
    VCMaterialDesignIconCode.md_switch_video                ,
    VCMaterialDesignIconCode.md_tag_faces                   ,
    VCMaterialDesignIconCode.md_texture                     ,
    VCMaterialDesignIconCode.md_timelapse                   ,
    VCMaterialDesignIconCode.md_timer                       ,
    VCMaterialDesignIconCode.md_timer_3                     ,
    VCMaterialDesignIconCode.md_timer_10                    ,
    VCMaterialDesignIconCode.md_timer_auto                  ,
    VCMaterialDesignIconCode.md_timer_off                   ,
    VCMaterialDesignIconCode.md_tonality                    ,
    VCMaterialDesignIconCode.md_transform                   ,
    VCMaterialDesignIconCode.md_tune                        ,
    VCMaterialDesignIconCode.md_wb_auto                     ,
    VCMaterialDesignIconCode.md_wb_cloudy                   ,
    VCMaterialDesignIconCode.md_wb_incandescent             ,
    VCMaterialDesignIconCode.md_wb_irradescent              ,
    VCMaterialDesignIconCode.md_wb_sunny                    ,
    VCMaterialDesignIconCode.md_beenhere                    ,
    VCMaterialDesignIconCode.md_directions                  ,
    VCMaterialDesignIconCode.md_directions_bike             ,
    VCMaterialDesignIconCode.md_directions_bus              ,
    VCMaterialDesignIconCode.md_directions_car              ,
    VCMaterialDesignIconCode.md_directions_ferry            ,
    VCMaterialDesignIconCode.md_directions_subway           ,
    VCMaterialDesignIconCode.md_directions_train            ,
    VCMaterialDesignIconCode.md_directions_transit          ,
    VCMaterialDesignIconCode.md_directions_walk             ,
    VCMaterialDesignIconCode.md_flight                      ,
    VCMaterialDesignIconCode.md_hotel                       ,
    VCMaterialDesignIconCode.md_layers                      ,
    VCMaterialDesignIconCode.md_layers_clear                ,
    VCMaterialDesignIconCode.md_local_airport               ,
    VCMaterialDesignIconCode.md_local_atm                   ,
    VCMaterialDesignIconCode.md_local_attraction            ,
    VCMaterialDesignIconCode.md_local_bar                   ,
    VCMaterialDesignIconCode.md_local_cafe                  ,
    VCMaterialDesignIconCode.md_local_car_wash              ,
    VCMaterialDesignIconCode.md_local_convenience_store     ,
    VCMaterialDesignIconCode.md_local_drink                 ,
    VCMaterialDesignIconCode.md_local_florist               ,
    VCMaterialDesignIconCode.md_local_gas_station           ,
    VCMaterialDesignIconCode.md_local_grocery_store         ,
    VCMaterialDesignIconCode.md_local_hospital              ,
    VCMaterialDesignIconCode.md_local_hotel                 ,
    VCMaterialDesignIconCode.md_local_laundry_service       ,
    VCMaterialDesignIconCode.md_local_library               ,
    VCMaterialDesignIconCode.md_local_mall                  ,
    VCMaterialDesignIconCode.md_local_movies                ,
    VCMaterialDesignIconCode.md_local_offer                 ,
    VCMaterialDesignIconCode.md_local_parking               ,
    VCMaterialDesignIconCode.md_local_pharmacy              ,
    VCMaterialDesignIconCode.md_local_phone                 ,
    VCMaterialDesignIconCode.md_local_pizza                 ,
    VCMaterialDesignIconCode.md_local_play                  ,
    VCMaterialDesignIconCode.md_local_post_office           ,
    VCMaterialDesignIconCode.md_local_print_shop            ,
    VCMaterialDesignIconCode.md_local_restaurant            ,
    VCMaterialDesignIconCode.md_local_see                   ,
    VCMaterialDesignIconCode.md_local_shipping              ,
    VCMaterialDesignIconCode.md_local_taxi                  ,
    VCMaterialDesignIconCode.md_location_history            ,
    VCMaterialDesignIconCode.md_map                         ,
    VCMaterialDesignIconCode.md_my_location                 ,
    VCMaterialDesignIconCode.md_navigation                  ,
    VCMaterialDesignIconCode.md_pin_drop                    ,
    VCMaterialDesignIconCode.md_place                       ,
    VCMaterialDesignIconCode.md_rate_review                 ,
    VCMaterialDesignIconCode.md_restaurant_menu             ,
    VCMaterialDesignIconCode.md_satellite                   ,
    VCMaterialDesignIconCode.md_store_mall_directory        ,
    VCMaterialDesignIconCode.md_terrain                     ,
    VCMaterialDesignIconCode.md_traffic                     ,
    VCMaterialDesignIconCode.md_apps                        ,
    VCMaterialDesignIconCode.md_cancel                      ,
    VCMaterialDesignIconCode.md_arrow_drop_down_circle      ,
    VCMaterialDesignIconCode.md_arrow_drop_down             ,
    VCMaterialDesignIconCode.md_arrow_drop_up               ,
    VCMaterialDesignIconCode.md_arrow_back                  ,
    VCMaterialDesignIconCode.md_arrow_forward               ,
    VCMaterialDesignIconCode.md_check                       ,
    VCMaterialDesignIconCode.md_close                       ,
    VCMaterialDesignIconCode.md_chevron_left                ,
    VCMaterialDesignIconCode.md_chevron_right               ,
    VCMaterialDesignIconCode.md_expand_less                 ,
    VCMaterialDesignIconCode.md_expand_more                 ,
    VCMaterialDesignIconCode.md_fullscreen                  ,
    VCMaterialDesignIconCode.md_fullscreen_exit             ,
    VCMaterialDesignIconCode.md_menu                        ,
    VCMaterialDesignIconCode.md_more_horiz                  ,
    VCMaterialDesignIconCode.md_more_vert                   ,
    VCMaterialDesignIconCode.md_refresh                     ,
    VCMaterialDesignIconCode.md_unfold_less                 ,
    VCMaterialDesignIconCode.md_unfold_more                 ,
    VCMaterialDesignIconCode.md_adb                         ,
    VCMaterialDesignIconCode.md_bluetooth_audio             ,
    VCMaterialDesignIconCode.md_disc_full                   ,
    VCMaterialDesignIconCode.md_dnd_forwardslash            ,
    VCMaterialDesignIconCode.md_do_not_disturb              ,
    VCMaterialDesignIconCode.md_drive_eta                   ,
    VCMaterialDesignIconCode.md_event_available             ,
    VCMaterialDesignIconCode.md_event_busy                  ,
    VCMaterialDesignIconCode.md_event_note                  ,
    VCMaterialDesignIconCode.md_folder_special              ,
    VCMaterialDesignIconCode.md_mms                         ,
    VCMaterialDesignIconCode.md_more                        ,
    VCMaterialDesignIconCode.md_network_locked              ,
    VCMaterialDesignIconCode.md_phone_bluetooth_speaker     ,
    VCMaterialDesignIconCode.md_phone_forwarded             ,
    VCMaterialDesignIconCode.md_phone_in_talk               ,
    VCMaterialDesignIconCode.md_phone_locked                ,
    VCMaterialDesignIconCode.md_phone_missed                ,
    VCMaterialDesignIconCode.md_phone_paused                ,
    VCMaterialDesignIconCode.md_play_download               ,
    VCMaterialDesignIconCode.md_play_install                ,
    VCMaterialDesignIconCode.md_sd_card                     ,
    VCMaterialDesignIconCode.md_sim_card_alert              ,
    VCMaterialDesignIconCode.md_sms                         ,
    VCMaterialDesignIconCode.md_sms_failed                  ,
    VCMaterialDesignIconCode.md_sync                        ,
    VCMaterialDesignIconCode.md_sync_disabled               ,
    VCMaterialDesignIconCode.md_sync_problem                ,
    VCMaterialDesignIconCode.md_system_update               ,
    VCMaterialDesignIconCode.md_tap_and_play                ,
    VCMaterialDesignIconCode.md_time_to_leave               ,
    VCMaterialDesignIconCode.md_vibration                   ,
    VCMaterialDesignIconCode.md_voice_chat                  ,
    VCMaterialDesignIconCode.md_vpn_lock                    ,
    VCMaterialDesignIconCode.md_cake                        ,
    VCMaterialDesignIconCode.md_domain                      ,
    VCMaterialDesignIconCode.md_location_city               ,
    VCMaterialDesignIconCode.md_mood                        ,
    VCMaterialDesignIconCode.md_notifications_none          ,
    VCMaterialDesignIconCode.md_notifications               ,
    VCMaterialDesignIconCode.md_notifications_off           ,
    VCMaterialDesignIconCode.md_notifications_on            ,
    VCMaterialDesignIconCode.md_notifications_paused        ,
    VCMaterialDesignIconCode.md_pages                       ,
    VCMaterialDesignIconCode.md_party_mode                  ,
    VCMaterialDesignIconCode.md_group                       ,
    VCMaterialDesignIconCode.md_group_add                   ,
    VCMaterialDesignIconCode.md_people                      ,
    VCMaterialDesignIconCode.md_people_outline              ,
    VCMaterialDesignIconCode.md_person                      ,
    VCMaterialDesignIconCode.md_person_add                  ,
    VCMaterialDesignIconCode.md_person_outline              ,
    VCMaterialDesignIconCode.md_plus_one                    ,
    VCMaterialDesignIconCode.md_poll                        ,
    VCMaterialDesignIconCode.md_public                      ,
    VCMaterialDesignIconCode.md_school                      ,
    VCMaterialDesignIconCode.md_share                       ,
    VCMaterialDesignIconCode.md_whatshot                    ,
    VCMaterialDesignIconCode.md_check_box                   ,
    VCMaterialDesignIconCode.md_check_box_outline_blank     ,
    VCMaterialDesignIconCode.md_radio_button_off            ,
    VCMaterialDesignIconCode.md_radio_button_on             ,
    VCMaterialDesignIconCode.md_star                        ,
    VCMaterialDesignIconCode.md_star_half                   ,
    VCMaterialDesignIconCode.md_star_outline              
  ];
}

@end
